"""
End-to-end smoke test for the eBay Consignments module.

Run against any environment to confirm that the full lifecycle persists to the
database and reads back correctly:

    cd backend
    python scripts/smoke_ebay_consignments.py

Required:
    DATABASE_URL or DATABASE_URL_SYNC pointing at a Postgres database.

What it does:
    1. Ensures the migration is applied
    2. Creates a consigner
    3. Creates an agreement with two items (using the agreement-level fee%)
    4. Adds a third item via the items endpoint
    5. Records a sale on one item
    6. Generates a monthly payout for that sale
    7. Reads back stats, agreement detail, items list, payout
    8. Marks the payout paid
    9. Cleans up everything it created (rolls back via deletes)

Exits 0 on success, non-zero on any failure.  Uses the service layer directly
(not HTTP) so it doesn't need the FastAPI server running.
"""

from __future__ import annotations

import asyncio
import os
import sys
import traceback
from datetime import date, datetime, timezone
from decimal import Decimal
from pathlib import Path
from uuid import UUID

# Make 'app' importable when run from anywhere
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def _green(s):  return f"\033[32m{s}\033[0m"
def _red(s):    return f"\033[31m{s}\033[0m"
def _bold(s):   return f"\033[1m{s}\033[0m"


async def main() -> int:
    print(_bold("\n=== eBay Consignments smoke test ===\n"))

    # ----------------------------------------------------------
    # 1. Apply migration
    # ----------------------------------------------------------
    from app.services.ebay_consignment_migrations import ensure_ebay_consignment_schema
    if not ensure_ebay_consignment_schema():
        print(_red("FAIL  could not apply migration. Check DATABASE_URL and try again."))
        return 1
    print(_green("OK    migration applied / schema in place"))

    from app.database import AsyncSessionLocal
    from app.services.ebay_consignment_service import EbayConsignmentService

    async with AsyncSessionLocal() as db:
        svc = EbayConsignmentService(db)

        created_consigner = None
        created_agreement = None
        created_payout = None

        try:
            # ----------------------------------------------------------
            # 2. Create consigner
            # ----------------------------------------------------------
            consigner = await svc.create_consigner(
                name="SMOKE TEST – delete me",
                email="smoke@example.com",
                phone="555-0000",
                street_address="1 Test Way",
                city="Testville",
                state="IL",
                postal_code="00001",
                country="USA",
                default_payout_percent=Decimal("80.00"),  # consigner gets 80%, IDGAS keeps 20%
                payment_method="Venmo",
                payment_details="@smoke",
                is_active=True,
                notes="autogenerated by smoke_ebay_consignments.py",
            )
            created_consigner = consigner.id
            print(_green(f"OK    created consigner {consigner.id}"))

            # ----------------------------------------------------------
            # 3. Create agreement w/ two items
            # ----------------------------------------------------------
            agreement = await svc.create_agreement(
                consigner_id=consigner.id,
                agreement_date=date.today(),
                payout_percent=Decimal("80.00"),
                items=[
                    {
                        "title": "Smoke Item A",
                        "description": "Desc A",
                        "category": "Memorabilia",
                        "condition": "NM",
                        "minimum_price": Decimal("100.00"),
                    },
                    {
                        "title": "Smoke Item B",
                        "description": None,
                        "category": None,
                        "condition": "EX",
                        "minimum_price": Decimal("50.00"),
                    },
                ],
                notes="smoke",
            )
            created_agreement = agreement.id
            assert agreement.agreement_number, "agreement_number should be auto-generated"
            assert len(agreement.items) == 2, f"expected 2 items, got {len(agreement.items)}"
            print(_green(f"OK    created agreement {agreement.agreement_number} with 2 items"))

            # ----------------------------------------------------------
            # 4. Add a third item via items endpoint
            # ----------------------------------------------------------
            third = await svc.add_item(
                agreement.id,
                title="Smoke Item C",
                minimum_price=Decimal("250.00"),
                condition="LN",
            )
            print(_green(f"OK    added third item {third.id}"))

            # ----------------------------------------------------------
            # 5. Record a sale on item B (the cheapest)
            # ----------------------------------------------------------
            full_agreement = await svc.get_agreement(agreement.id)
            item_b = next(i for i in full_agreement.items if i.title == "Smoke Item B")
            sale = await svc.record_sale(
                item_b.id,
                sold_price=Decimal("85.00"),
                sold_at=datetime.now(timezone.utc),
                ebay_fees=Decimal("8.50"),
                payment_fees=Decimal("2.50"),
                shipping_cost=Decimal("5.00"),
                buyer_info="smoke buyer",
            )
            assert sale.status == "sold", f"expected status sold, got {sale.status}"
            print(_green(f"OK    recorded sale - status={sale.status} sold_price={sale.sold_price}"))

            # ----------------------------------------------------------
            # 6. Generate monthly payout for the sale's period
            # ----------------------------------------------------------
            now = datetime.now(timezone.utc)
            payout = await svc.generate_payout(
                consigner_id=consigner.id,
                year=now.year,
                month=now.month,
                notes="smoke",
            )
            created_payout = payout.id
            assert payout.item_count == 1, f"expected 1 item in payout, got {payout.item_count}"
            # Math check: gross 85 - eBay 8.50 - other 7.50 - 20% commission (17.00) = 52.00
            expected_commission = Decimal("17.00")
            expected_net = Decimal("52.00")
            assert payout.total_idgas_fee == expected_commission, (
                f"commission: expected {expected_commission}, got {payout.total_idgas_fee}"
            )
            assert payout.net_payout == expected_net, (
                f"net payout: expected {expected_net}, got {payout.net_payout}"
            )
            print(_green(
                f"OK    generated payout: gross={payout.total_gross} "
                f"commission={payout.total_idgas_fee} net={payout.net_payout}"
            ))

            # ----------------------------------------------------------
            # 7. Read back via list-items endpoint and stats
            # ----------------------------------------------------------
            items = await svc.list_items(consigner_id=consigner.id)
            assert len(items) == 3, f"expected 3 items in inventory, got {len(items)}"
            sold_items = [i for i in items if i.status == "sold"]
            assert len(sold_items) == 1, f"expected 1 sold item, got {len(sold_items)}"
            print(_green(f"OK    list_items returned {len(items)} items ({len(sold_items)} sold)"))

            stats = await svc.get_consigner_stats(consigner.id)
            assert stats["items_sold"] == 1
            assert stats["lifetime_gross"] == Decimal("85.00")
            print(_green(f"OK    consigner stats: sold={stats['items_sold']} "
                         f"gross={stats['lifetime_gross']} payout={stats['lifetime_payout']}"))

            # ----------------------------------------------------------
            # 8. Mark paid
            # ----------------------------------------------------------
            paid = await svc.mark_payout_paid(
                payout.id,
                paid_at=datetime.now(timezone.utc),
                paid_method="Venmo",
                paid_reference="SMOKE-REF",
            )
            assert paid.is_paid, "expected payout.is_paid==True after mark_payout_paid"
            print(_green(f"OK    marked payout paid (ref={paid.paid_reference})"))

            print(_bold(_green("\n=== ALL SMOKE TESTS PASSED ===\n")))
            return 0

        except AssertionError as e:
            print(_red(f"\nFAIL  assertion failed: {e}"))
            traceback.print_exc()
            return 1
        except Exception as e:
            print(_red(f"\nFAIL  unexpected error: {e}"))
            traceback.print_exc()
            return 1
        finally:
            # ----------------------------------------------------------
            # 9. Cleanup
            # ----------------------------------------------------------
            try:
                # Unpaid payouts can be deleted; ours is paid - so we have to
                # release manually
                if created_payout:
                    p = await svc.get_payout(created_payout)
                    if p:
                        # Force unpaid so delete works, then delete
                        p.is_paid = False
                        await db.commit()
                        await svc.delete_payout(created_payout)
                if created_agreement:
                    await svc.delete_agreement(created_agreement)
                if created_consigner:
                    # Mark inactive then delete via raw query (no service method)
                    from app.models.ebay_consignments import EbayConsigner
                    from sqlalchemy import delete
                    await db.execute(delete(EbayConsigner).where(EbayConsigner.id == created_consigner))
                    await db.commit()
                print(_green("OK    cleanup complete - test data removed"))
            except Exception as e:
                print(_red(f"WARN  cleanup failed (you may have stragglers): {e}"))


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
